### ISSUE TITLE
Can you share your hyper parameters ?

### ISSUE THREAD

**Issue by yuchenlichuck** [ma-xu/pointMLP-pytorch#11]
Rt

**Comment by ma-xu** [comment]
@yuchenlichuck Could you please clarify what do you mean by hyper parameters?

if it means the parameters in "parser", you can direct use the defult values (except --model).

**Comment by ma-xu** [comment]
@yuchenlichuck Not yet scince I have to  work on another submission recently. See here https://github.com/ma-xu/pointMLP-pytorch/issues/6#issuecomment-1053660028

**Comment by ma-xu** [comment]
@yuchenlichuck I will close this issue since there is no further discussion. Feel free to reopen it if necessary.
