### ISSUE TITLE
PointMLP-Elite in part segmentation?

### ISSUE THREAD

**Issue by eunzihong** [ma-xu/pointMLP-pytorch#12]
Hi and Thanks for your great work.

I'm just wondering if you have had or tested PointMLP-'Elite' version for part segmentation while you have them for classification works. 
And if so, do you have any plan for sharing the codes as well? 🙏

Thank you. 😊

**Comment by ma-xu** [comment]
@eunzihong We didn't test elite for part-seg.  our can easily implement it by changing thr settings.

**Comment by eunzihong** [comment]
Ok. Great! Thank you for reply 👍

**Comment by ma-xu** [comment]
@eunzihong I will close this issue since there is no further discussion. Feel free to reopen it if necessary.
