### ISSUE TITLE
About ShapeNet Part visualization？

### ISSUE THREAD

**Issue by swzaaaaaaa** [ma-xu/pointMLP-pytorch#16]
Can you provide the code of part segmentation visualization?Thanks.

**Comment by ma-xu** [comment]
Sure.
See here: https://drive.google.com/file/d/1uHba4V3LawtWzTYuZ8FplpfosIWOZ3VP/view?usp=sharing

It is not cleaned, but it works. Feel free to modify it according to your codebase.

**Comment by swzaaaaaaa** [comment]
Received,thank you.

**Comment by Emenent758** [comment]
> Can you provide the code of part segmentation visualization?Thanks.

Hello !
Were you able to run the script for visualization of part segm data set?
When I try to run, I get the following error.
![image](https://user-images.githubusercontent.com/67109198/181252544-60055c50-f89c-4444-af8e-036ac7d7ca6c.png)

thanks for your time
