### ISSUE TITLE
GEOMETRIC AFFINE MODULE

### ISSUE THREAD

**Issue by qingfeng0830** [ma-xu/pointMLP-pytorch#17]
Regarding the part of the geometric mapping module, why does the point cloud show a normal distribution after such an operation?

**Comment by qingfeng0830** [comment]
Thanks for your answer. And what is the reason for this transformation? Is the original irregular local point cloud mapped to a relatively regular distribution?

**Comment by ma-xu** [comment]
The reason behind this module is that we want to know if there is a simple method to make up the loss of local operators (besides the MLP extractor). After several experiments, we get this module.

Is the original irregular local point cloud mapped to a relatively regular distribution? 
It's hard to tell if this could be considered as a reason.

**Comment by ma-xu** [comment]
@qingfeng0830 I will close this issue since there is no further discussion. Feel free to reopen it if necessary.
