### ISSUE TITLE
Add Skip connection in the segmentation task

### ISSUE THREAD

**Issue by Chen-yuiyui** [ma-xu/pointMLP-pytorch#18]
Hi!Thank you for the great work. Now I want to use your net for the Semantic Segmentation task, so I want to modify the Part Segmentation model. It seems like your model architecture only replaced the PointNet's backbone. Can I add skip connection after the set abstraction operation(like pointnet++)? Have you tried the Semantic Segmentation?

**Comment by ma-xu** [comment]
Hi, thanks for your interest. Sure, you can do that. We didn't try this but it should work.

**Comment by ma-xu** [comment]
@Chen-yuiyui I will close this issue since there is no further discussion. Feel free to reopen it if necessary.
