### ISSUE TITLE
Hi，thanks for your great work.But I have some questions ,and I'd like to ask you.Thank you su much.

### ISSUE THREAD

**Issue by sh4175515** [ma-xu/pointMLP-pytorch#19]
(pointmlp) D:\Downloads\pointmlp\pointnet2_ops_lib>python setup.py install
running install
D:\Anaconda\envs\pointmlp\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
D:\Anaconda\envs\pointmlp\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing pointnet2_ops.egg-info\PKG-INFO
writing dependency_links to pointnet2_ops.egg-info\dependency_links.txt
writing requirements to pointnet2_ops.egg-info\requires.txt
writing top-level names to pointnet2_ops.egg-info\top_level.txt
reading manifest file 'pointnet2_ops.egg-info\SOURCES.txt'
writing manifest file 'pointnet2_ops.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
error: [WinError 2] The system could not find the specified file.。

**Comment by ma-xu** [comment]
@sh4175515 Not sure if this lib can work on Windows (we suggest Ubuntu/Lunix). Instead of using pointnet2_ops_lib lib, you can also consider the well-developed **pytorch3d** or **pytorch_geometric**. See here: https://github.com/ma-xu/pointMLP-pytorch/issues/2#issuecomment-1079764871

**Comment by ma-xu** [comment]
@sh4175515 Hi, if there are no further discussions, I will close this issue. Feel free to re-open again if necessary.
