### ISSUE TITLE
install pointnet2_ops error

### ISSUE THREAD

**Issue by LiXinZhana** [ma-xu/pointMLP-pytorch#22]

**Comment by LiXinZhana** [comment]
![图片](https://user-images.githubusercontent.com/49310451/164952769-0173968e-17fb-4c23-8792-9f2e483b58cb.png)

**Comment by ma-xu** [comment]
@LiXinZhana From your error log, there may be something wrong with your gcc (e.g., gcc version).

For some potential solutions, please see https://github.com/ma-xu/pointMLP-pytorch/issues/20, https://github.com/ma-xu/pointMLP-pytorch/issues/2.

**Comment by LiXinZhana** [comment]
@ma-xu Thank you! I will try to change my gcc version. What gcc version do you use？

**Comment by ma-xu** [comment]
@LiXinZhana Ubuntu GCC 5.5

**Comment by LiXinZhana** [comment]
@ma-xu My gcc version is 
![图片](https://user-images.githubusercontent.com/49310451/164954202-04943ef8-e802-4c43-8f76-f0c6f6bec14c.png)

**Comment by ma-xu** [comment]
> @ma-xu My gcc version is ![图片](https://user-images.githubusercontent.com/49310451/164954202-04943ef8-e802-4c43-8f76-f0c6f6bec14c.png)

emmm ... Could you please post the whole error log?

**Comment by LiXinZhana** [comment]
> 

![图片](https://user-images.githubusercontent.com/49310451/164960988-f21373f6-20b2-4b8f-91b4-e93d73fe7cf1.png)
![图片](https://user-images.githubusercontent.com/49310451/164961951-ebb1bfe9-9119-4bd4-a4c5-bcff212087a5.png)

**Comment by ma-xu** [comment]
@LiXinZhana Sry that I cannot find the reason. An optional solution is that you can avoid installing this lib via https://github.com/ma-xu/pointMLP-pytorch/issues/2#issuecomment-1079764871

**Comment by LiXinZhana** [comment]
@ma-xu Thanks a lot! I didn't use these when I first reproduced this code. But it's too slow.Thank you for your work！
