### ISSUE TITLE
About partseg 

### ISSUE THREAD

**Issue by chenyanjie519** [ma-xu/pointMLP-pytorch#23]
Hello, is there any test code for component splitting? How should I see the visual result of component segmentation?

**Comment by ma-xu** [comment]
@chenyanjie519 Hi, if you mean how to visualize the part segmentation results? If yes, please see: https://github.com/ma-xu/pointMLP-pytorch/issues/16#issuecomment-1080799125.

Codes here: https://drive.google.com/file/d/1uHba4V3LawtWzTYuZ8FplpfosIWOZ3VP/view?usp=sharing

It is not cleaned, but it works. Feel free to modify it according to your codebase.
