### ISSUE TITLE
LocalGrouper is different from the description in the paper

### ISSUE THREAD

**Issue by Qianyu1998** [ma-xu/pointMLP-pytorch#24]
Thanks to the author for the code. I would like to ask a question, the variable σ is calculated in the code is not the same as the description in the paper.

**Comment by Qianyu1998** [comment]
我想请问一下，这里的std和论文里的 σ的计算方式好像不一样。还有一个问题，请问论文中的方法是受什么启发呀，感觉这里是不是算是对输入数据进行了一次可学习的归一化（不知道理解的对不对）

在 2022-05-04 22:49:05，"Xu Ma" ***@***.***> 写道：

Thanks to the author for the code. I would like to ask a question, the variable σ is calculated in the code is not the same as the description in the paper.
@Qianyu1998 Thanks for your interest. Could you please point out where the difference is? in case there are some misunderstandings or I can fix it.

**Comment by ma-xu** [comment]
@Qianyu1998 
For \sigma, please double-check, looks like there is no differences.

I assume you are talking about the refine module. The motivation is that we should provide a simple method that can avoid complex local computations, operations like normalization perfectly match this requirements.

**Comment by Martin-Liao** [comment]
Thanks for your interpretation! I guess the affine module plays the role of spatial transformer in PointNet ,which  maps  input features to a canonical space,right?(Yeah it seems that more relative to normalization...)

> @Qianyu1998 For \sigma, please double-check, looks like there is no differences.
> 
> I assume you are talking about the refine module. The motivation is that we should provide a simple method that can avoid complex local computations, operations like normalization perfectly match this requirements.
