### ISSUE TITLE
Thanks a lot for sharing the code! I have some questions about part segment.

### ISSUE THREAD

**Issue by xindeng98** [ma-xu/pointMLP-pytorch#25]
Are the best parameters is the default parameters?Also I noticed that in the classification you use the default initialization, but in this task you use the xavier initialization method, is there any intuitive explanation for this? I hope to get your reply, maybe the parameter settings. Thank you very much for your contribution!

**Comment by ma-xu** [comment]
@xindeng98 
1. yes.
2. I just followed previous works like GDANet for part segmentation task. 
Please let me know if you have any further questions.

**Comment by xindeng98** [comment]
> @xindeng98
> 
> 1. yes.
> 2. I just followed previous works like GDANet for part segmentation task.
>    Please let me know if you have any further questions.

Thank you for such a quick reply! Can I get the training log of the part segment from you? I want to quickly judge whether my idea is feasible according to the comparison of loss descent speed.

**Comment by ma-xu** [comment]
@xindeng98 Sure. You can check [commit:d2b8dbaa](http://github.com/13952522076/pointMLP-pytorch/tree/d2b8dbaa06eb6176b222dcf2ad248f8438582026). The log files are provided here: [[anonymous google drive]](https://drive.google.com/drive/folders/1Jn9HNpPsrq-1XqSmOUtw4cwPMjsIiIpz?usp=sharing)

**Comment by xindeng98** [comment]
Thanks a lot.
