### ISSUE TITLE
Install ''pip install pointnet2_ops_lib/.''

### ISSUE THREAD

**Issue by Serendipityo1** [ma-xu/pointMLP-pytorch#26]
Thanks to the author for the code.
In the Install section of the Github page
''pip install pointnet2_ops_lib/.''
for what purpose? Is it a package or file?
Terminal display:
''ERROR: Invalid requirement: 'pointnet2_ops_lib/.'
Hint: It looks like a path. File 'pointnet2_ops_lib/.' does not exist.''

**Comment by ma-xu** [comment]
@Serendipityo1 
This is a package to run fps on gpu for fast speed.

Please run the installation on Unbuntu (under pointMLP-pytorch folder)
