### ISSUE TITLE
There is a little gap between my results and those in the paper

### ISSUE THREAD

**Issue by hht1996ok** [ma-xu/pointMLP-pytorch#27]
First, thank you for your work, I ran 300 epochs according to your code, however the OA was 93.85 and mAcc was 91.24, I would like to ask why there is a little gap between paper.

**Comment by ma-xu** [comment]
@hht1996ok please see # https://github.com/ma-xu/pointMLP-pytorch/issues/1#issuecomment-1032642340

It is common to get different results by runing same codes for ModelNet40 benchmark due to the randomness.

**Comment by ma-xu** [comment]
@hht1996ok Also, please see News & Updates in README.md: 
⏩ Questions on ModelNet40 classification reproduction
The performance on ModelNet40 of almost all methods are not stable, see (https://github.com/CVMI-Lab/PAConv/issues/9#issuecomment-873371422). If you run the same codes for several times, you will get different results. Also, the randomness of ModelNet40 is our motivation to experiment on ScanObjectNN benchmark, and to report the mean/std results of several runs.

**Comment by hht1996ok** [comment]
Thank you for your reply！
