### ISSUE TITLE
运行main.py出现错误

### ISSUE THREAD

**Issue by xiaoyangyang123** [ma-xu/pointMLP-pytorch#29]
昨天跑起来一次，但是今天来了看到中途报错卡顿了（未拍照），重新运行时便提醒该错误，请问作者遇到过吗？该如何解决呢，百度了一下，但是并未找到解决方案
报错：KeyError：'PointMLP'
![IMG_9530](https://user-images.githubusercontent.com/87469804/168022941-a340f289-eb5e-4f97-95b7-0b8a7dd27996.JPG)
。

**Comment by ma-xu** [comment]
@xiaoyangyang123 
python main.py --model pointMLP

pointMLP instead of PointMLP

**Comment by xiaoyangyang123** [comment]
好的，谢谢作者
