### ISSUE TITLE
part segmentation

### ISSUE THREAD

**Issue by junshengzhou** [ma-xu/pointMLP-pytorch#3]
Hi,
Thank you for sharing your code! But I have some difficult in training ShapeNetPart segmentation. I found that there is no folder named 'util' under 'part_segmentation' , so I can't find 'to_categorical', 'PartNormalDataset' etc. And I guess Class 'ShapeNetPart' might be another version of 'PartNormalDataset', but it seems to have different parameter.

**Comment by ma-xu** [comment]
@junshengzhou  Thanks for your remind. Will double check and fix it soon.

**Comment by swzaaaaaaa** [comment]
There is indeed this problem. Has it been solved?

**Comment by ma-xu** [comment]
@swzaaaaaaa See https://github.com/ma-xu/pointMLP-pytorch/issues/9#issuecomment-1055728573

We will update it after Mar/10 because we are busy with another project recently.

**Comment by ma-xu** [comment]
@swzaaaaaaa @junshengzhou 
Thanks for your interest. I just double-checked: mistakenly uploaded the wrong folder in experiments.
Our development codes are based on PAConv, GDANet(yes), and Curevenet. We tried several implementations; as a result, we uploaded the wrong folder. You can see it in my pointsmlp repo, which is our development repo.
It is fixed now. Please have a try and let me know if there are still any issues.

**Comment by ma-xu** [comment]
@swzaaaaaaa @junshengzhou I will close this issue since there is no further discussion. Feel free to reopen it if necessary.
