### ISSUE TITLE
Number of parameters in the paper

### ISSUE THREAD

**Issue by ListIndexOutOfRange** [ma-xu/pointMLP-pytorch#32]
Hi, thanks again for your work and your responsiveness in responding to issues.

I've got another minor issue, I'm sure it's a small misunderstanding from me, sorry in advance. 
In your paper on Table 2 you claim that PointMLP and PointMLP-Elite have respectively 12.6 and 0.68 M parameters. 
However if i run something like 
```python
print_num_params = lambda net: print(f"{sum(p.numel() for p in net.parameters() if p.requires_grad):,}")
print_num_params(pointMLP())
print_num_params(pointMLPElite())
```
I get 13,238,504 and 716,232 respectively. 

Where does the difference come from ? 

Thanks in advance !

**Comment by ma-xu** [comment]
@ListIndexOutOfRange Thanks a lot for your interest.

For PointMLP, 13238504 = 13238504/1024.0 K = 12928.2265625K = 12928.2265625/1024.0G = 12.625221252441406~=12.6G

For PointMLP-Elite, 716232 = 716232/1024.0 K = 699.4453125 K = 699.4453125/1024 G = 0.6830520629882812 ~=0.68G
