### ISSUE TITLE
FPS and KNN are not hardware friendly and efficient

### ISSUE THREAD

**Issue by zhouchch3** [ma-xu/pointMLP-pytorch#33]
Thanks for your great work!
Although the proposed network is simple with just residual MLPs, Geometric Affine Module cannot be executed efficiently in hardware. It is because when I design ASIC for PointMLP, I find in FPS and KNN phases, points must be processed serially not in parallel. Can you provide some advice about the efficient process of FPS and KNN in hardware? Or, how FPS and KNN can be modified to be hardware friendly?

Thank you very much!

**Comment by ma-xu** [comment]
@zhouchch3 Thanks for your interest.

Unfortunately, I don't have any experience with hardware. Both FPS and KNN are well-known algrithoms, maybe there are some ASIC  hardware-friendly implementations (not sure). You can try to find some online.

**Comment by zhouchch3** [comment]
Thanks for your advice! I'll try
