### ISSUE TITLE
Alternate to pointnet2_ops_lib

### ISSUE THREAD

**Issue by ShuvenduRoy** [ma-xu/pointMLP-pytorch#36]
Hi,

First of all, thank you for sharing the code for this paper. 

I was not able to install pointnet2_ops_lib because of cuda version conflict in my local PC. 
But I have found that the only place I need this is 'pointnet2_utils.furthest_point_sample'.
There is a commented alternate to this function in the code in the following line.

https://github.com/ma-xu/pointMLP-pytorch/blob/8d8e46cbf4f2089ee38711c07e1edd15c5d71928/classification_ModelNet40/models/pointmlp.py#L159

Could you please let me know what will happen if I use this ensted? Will this lower the accuracy of the model?

**Comment by ma-xu** [comment]
You can use this one instead: 
https://github.com/ma-xu/pointMLP-pytorch/blob/8d8e46cbf4f2089ee38711c07e1edd15c5d71928/classification_ModelNet40/models/pointmlp.py#L160

You should get similar results but much slower (maybe half) training and inference speeds.

**Comment by ShuvenduRoy** [comment]
I see. Thanks a lot for the information.
