### ISSUE TITLE
Why is there only 9480 ply_data_train  in modelnet40 dataset instead of 9483

### ISSUE THREAD

**Issue by libeike** [ma-xu/pointMLP-pytorch#37]

**Comment by ma-xu** [comment]
It may caused by different released version of the model (not sure).

Please refer the official dataset link: https://github.com/ma-xu/pointMLP-pytorch/blob/8d8e46cbf4f2089ee38711c07e1edd15c5d71928/classification_ModelNet40/data.py#L14

**Comment by libeike** [comment]
Training set really only has 9480 data in ’modelnet40_ply_hdf5_2048’ .

**Comment by libeike** [comment]
Will these three data have an effect on the results of the experiment?

**Comment by ma-xu** [comment]
> Will these three data have an effect on the results of the experiment?

Not sure if different verions will have some performance fluctuations. All our experiments are conducted on this version (as well as CurveNet, PAConv, GDANet, etc.)

**Comment by libeike** [comment]
> > Will these three data have an effect on the results of the experiment?
> 
> Not sure if different verions will have some performance fluctuations. All our experiments are conducted on this version (as well as CurveNet, PAConv, GDANet, etc.)

Thank you for your reply, thanks!
