### ISSUE TITLE
I was wondering how was the result on segmentation

### ISSUE THREAD

**Issue by yuchenlichuck** [ma-xu/pointMLP-pytorch#4]
Have you trained the method in segmentation, like s3dis, scannet?

**Comment by ma-xu** [comment]
@yuchenlichuck We didn’t try that.

**Comment by volare1996** [comment]
> haha, okay, thanks for your rapid replay!
Whether it is feasible to train the method in segmentation? thanks.

**Comment by ma-xu** [comment]
@volare1996 I assume the answer is yes. We would have a try in the summer.

**Comment by ma-xu** [comment]
@volare1996 @yuchenlichuck I will close this issue since there is no further discussion. Feel free to reopen it if necessary.
