### ISSUE TITLE
About how to get testing speed of PointNet++

### ISSUE THREAD

**Issue by Roywangj** [ma-xu/pointMLP-pytorch#41]
Hi:
I find you get speed of pointnet++ in Table 2. by this code(https://github.com/erikwijmans/Pointnet2_PyTorch). However, this code use [PyTorch Lightning](https://github.com/williamFalcon/pytorch-lightning) and [Hydra](https://hydra.cc/), i can only get training time of each epoch while unabling to get testing time, I'm wondering if you have any suggestion. It will help me a lot, thank you
<img width="1048" alt="pointnet2issuesforgithub" src="https://user-images.githubusercontent.com/48822865/172896584-a232951f-d266-4ed2-86c3-44e0725b3a30.png">
.

**Comment by ma-xu** [comment]
We use the model here: https://github.com/ma-xu/pointsMLP/blob/master/classification/models/pointnet2.py , which is our develop repo. 

You can simply copy pointnet2.py to models folder and add to __init__.py. Then, test pointnet++ as pointMLP.

**Comment by Roywangj** [comment]
Thank you! This repo helps a lot.

**Comment by ma-xu** [comment]
Thanks for your affirmation.
