### ISSUE TITLE
Have you tested PointMLP on semantic segmentation datasets?

### ISSUE THREAD

**Issue by whuhxb** [ma-xu/pointMLP-pytorch#43]
Hi @ma-xu 

Have you tested PointMLP on semantic segmentation datasets? For example, S3DIS dataset.

Thanks.

**Comment by ma-xu** [comment]
@whuhxb Hi, we didn't tested it in theis version.  We will add the semantic segmentation task iin our extension work. Thanks.

**Comment by ma-xu** [comment]
@whuhxb Issue closed since no further discussions. Feel free to re-open it if necessary.
