### ISSUE TITLE
pointnet2_ops_lib

### ISSUE THREAD

**Issue by AArutoria** [ma-xu/pointMLP-pytorch#45]
Dear author, first of all thank you for your efforts, this is a good project. But I have some questions to ask you. I want to run pointMLP.py first. But when running the code, it often reports an error: 
ModuleNotFoundError: No module named 'pointnet2_ops'
Then I read the Readme. Which
pip install pointnet2_ops_lib/. can not run. 
There will be ERROR: Invalid requirement: 'pointnet2_ops_lib/pointMLP2_ops'
Hint: It looks like a path. File 'pointnet2_ops_lib/pointMLP2_ops' does not exist.
hint. 
How can I solve it please? ? Looking forward to your perfect answer.

**Comment by ma-xu** [comment]
@AArutoria Make sure you are in /pointMLP-pytorch folder, and resintall it again. Please let me know if there is any other issues.

**Comment by AArutoria** [comment]
@ma-xu Thanks to the author, my problem has been solved. Thanks again for your dedication.
