### ISSUE TITLE
How to use normals or additional features?

### ISSUE THREAD

**Issue by sheshap** [ma-xu/pointMLP-pytorch#46]
Hi,

Great work and thanks for releasing the Code.
Can you please suggest how one can use additional features such as normals?

Thanks in Advance.

**Comment by ma-xu** [comment]
It is simple to achieve that. Just modify 3 to input channel number (e.g., 6) in the first embedding layer https://github.com/ma-xu/pointMLP-pytorch/blob/205669826d269972e2616b13198dd52f41c9992e/classification_ModelNet40/models/pointmlp.py#L289

**Comment by sheshap** [comment]
what changes are required for the data loader to read modelnet40_normal_resampled dataset with normals?

**Comment by ma-xu** [comment]
I'm using this version: https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip

You may need to figure out this issue by yourself  (I assume the data in modelnet40_normal_resampled would be [cordination; normal] 6 dimensions, please double-check).

**Comment by sheshap** [comment]
Thank you. I managed to write a data loader for the modelnet40_normal_resampled. Closing this issue.
