### ISSUE TITLE
farthest_point_sample

### ISSUE THREAD

**Issue by mahaotian-io** [ma-xu/pointMLP-pytorch#47]
I found in your pointmlp model that you have a function defined farthest_point_sample but you still use .furthest_point_sample function in the pointnet2_utils, and I want to ask, is there a difference between the two functions?

**Comment by ma-xu** [comment]
@mahaotian-io Hi, they are the same, but the self-defined function defined farthest_point_sample is in python and .furthest_point_sample is in cuda. We use the cuda version for fast training and inference.

**Comment by ma-xu** [comment]
> I would like to ask you about the "GEOMETRIC AFFINE MODULE" in the pointmlp model specific implementation.

Sure, what is ur question?

**Comment by mahaotian-io** [comment]
> "GEOMETRIC AFFINE MODULE"

How do you implement "GEOMETRIC AFFINE MODULE" in your code? I want to try to use this method in some other tasks.

**Comment by ma-xu** [comment]
@mahaotian-io You can find it in this module: https://github.com/ma-xu/pointMLP-pytorch/blob/205669826d269972e2616b13198dd52f41c9992e/classification_ModelNet40/models/pointmlp.py#L130
