### ISSUE TITLE
Please provide test.py for part segmentation experiment

### ISSUE THREAD

**Issue by Rabbia-Hassan** [ma-xu/pointMLP-pytorch#48]
Hello!
Thanks for shairing the code.
Please provide the test/evaluation code for part segmentation experiment, or please share the method to evaluate the pre-trained model for this particular experiment.

Look forward to your reply.
Thanks

**Comment by ma-xu** [comment]
Hi, it is simple to get the testing script from https://github.com/ma-xu/pointMLP-pytorch/blob/main/part_segmentation/main.py. You can simpfy the training script to get what you want (load pretrained and run test function).

**Comment by Rabbia-Hassan** [comment]
thanks for the reponse, but can you provide the simplified script for testing?

Regards

**Comment by ma-xu** [comment]
@Rabbia-Hassan I just noticed that we have implemented the eval codes in the main file. You can simply call it by:
python main.py --model [model_name] --exp_name [exp_name] [--other parameters] ```--eval```

Notice that make sure the pretrained model is saved in the folder that shares the same name as model_name.

Please let me know if you have any questions or concerns.

**Comment by Rabbia-Hassan** [comment]
thanks a lot for help, but actually the training doesn't proceed in my case, it just stucks here, while there is enough gpu memory available. (screenshot attached).
Please guide me.
![image](https://user-images.githubusercontent.com/102951740/181069604-8a8b284d-0ecc-45df-87ea-fad1954343b4.png)

**Comment by liuhui0401** [comment]
Sorry to bother you. I would like to ask if you can provide a pre-trained model for part segmentation? Thanks.

**Comment by ma-xu** [comment]
@liuhui0401 please see this issue: https://github.com/ma-xu/pointMLP-pytorch/issues/49

**Comment by liuhui0401** [comment]
> 

Thank you very much!
