### ISSUE TITLE
Pretrained models for part segmentation

### ISSUE THREAD

**Issue by Francisco-liu** [ma-xu/pointMLP-pytorch#49]
Hello!
Thanks for your great work!  Can you share the pretrained models for part segmentation experiments?
Look forward to your reply.
Thanks

**Comment by ma-xu** [comment]
Hi, thanks for your interest.
The checkpoints can be found here: [google drive](https://drive.google.com/drive/folders/1Jn9HNpPsrq-1XqSmOUtw4cwPMjsIiIpz?usp=sharing) at commit id [d2b8dbaa](http://github.com/13952522076/pointMLP-pytorch/tree/d2b8dbaa06eb6176b222dcf2ad248f8438582026)
Notice that the pretrained model is not bug-fixed version (which may leads to slightly unstable testing result).

**Comment by Francisco-liu** [comment]
thank you for your prompt reply.
thank you very much
