### ISSUE TITLE
how to apply the skip connection to PointNet++？

### ISSUE THREAD

**Issue by 515907651** [ma-xu/pointMLP-pytorch#5]
PointNet++ only apply skip connection to the Segmentation, how to apply it to classification?

**Comment by ma-xu** [comment]
@515907651 I assume you are talking about the Skip Connection Section in supplementary (as required by reviewer). 


In the  first PointNetSetAbstraction, we have MLP channel [64, 64, 128], one skip connection could be added.
In the second PointNetSetAbstraction, we have MLP channel mlp=[128, 128, 256], one skip connection could be added.
In total, two skip connections could be added for classification.
