### ISSUE TITLE
about multi gpu support 

### ISSUE THREAD

**Issue by Emenent758** [ma-xu/pointMLP-pytorch#50]
Hello !
Thank you for really nice work.
Please tell me how to run your code on a multi gpu machine? secondly, how much gpu memory is needed for segmentation's task? I have 12 gb gpu memory but when I put the model on training it gives cuda out of memory error right in the beginning, although the classification model trains fine on my machine,
Please guide.
Thanks

**Comment by ma-xu** [comment]
Hi, Thanks for your interest. 
I assume you can directly run on multi-gpu machine. Please let me know if any problems.
Should be around 20 GB (not very sure). You can reduce the batch size to fit your gpu.

**Comment by Emenent758** [comment]
when on try to run on multi gpu machine, it gets stucks both for classification and part segmentation, it doesnt show any error but doesnt proceed further.
![image](https://user-images.githubusercontent.com/67109198/181232156-2d94351a-3008-4f7a-9d03-a830a44178d2.png)
for segmentation
![image](https://user-images.githubusercontent.com/67109198/181233010-98c10702-c3e1-4265-8812-b74e1b02a863.png)
Also please find the screenshot for memory usgae when model is made to run.
![image](https://user-images.githubusercontent.com/67109198/181233190-b59386fb-fbd2-44ec-b0bc-63edc6a92e42.png)
Please guide.
Thank you for your time

**Comment by ma-xu** [comment]
@Emenent758 Sorry for the later reply. I have never met this issue previously. Does it work well on one gpu?

**Comment by ma-xu** [comment]
@Emenent758 I will close this issue since no further discussions. Feel free to reopen it if necessary.
