### ISSUE TITLE
GEOMETRIC AFFINE MODULE

### ISSUE THREAD

**Issue by AArutoria** [ma-xu/pointMLP-pytorch#51]
May I ask what part of the GEOMETRIC AFFINE MODULE code is? Looking forward to the author's answer

**Comment by ma-xu** [comment]
@AArutoria Hi, I remember that I responsed to you. The code is here: https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L171
Please let me know if any further questions.

**Comment by AArutoria** [comment]
Thanks to the author for answering questions. I have a few more questions. The first point: Figure 2 shows a stage of PointMLP, which shows that the point cloud is directly input into the GEOMETRIC AFFINE MODULE. But in Figure 6, the point cloud enters stage1 after the Embedding operation. Does this mean that both point clouds and embedded point clouds can be input into GEOMETRIC AFFINE MODULE? Second point: In Figure 6, I can't see where the GEOMETRIC AFFINE MODULE is. Is it in Embedding or in stage1? Thanks again for the author's answer

**Comment by AArutoria** [comment]
> @AArutoria Hi, I remember that I responsed to you. The code is here:
> 
> https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L171
> 
> 
> Please let me know if any further questions.

Thanks to the author for answering questions. I have a few more questions. The first point: Figure 2 shows a stage of PointMLP, which shows that the point cloud is directly input into the GEOMETRIC AFFINE MODULE. But in Figure 6, the point cloud enters stage1 after the Embedding operation. Does this mean that both point clouds and embedded point clouds can be input into GEOMETRIC AFFINE MODULE? Second point: In Figure 6, I can't see where the GEOMETRIC AFFINE MODULE is. Is it in Embedding or in stage1? Thanks again for the author's answer

**Comment by ma-xu** [comment]
@AArutoria 
1. yes. BTW, the inputs in figure 2 actually are features. we plot as points for better visualization. You can refer the codes for better understnading. 
2. It is in the aggregation. Please correct me if I remember wrong. 

Feel free to ask me if you have any further questions.

**Comment by AArutoria** [comment]
> @AArutoria
> 
> 1. yes. BTW, the inputs in figure 2 actually are features. we plot as points for better visualization. You can refer the codes for better understnading.
> 2. It is in the aggregation. Please correct me if I remember wrong.
> 
> Feel free to ask me if you have any further questions.

Thanks for your patient answer. I have a new understanding of your code
