### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by 1234923iuuu** [ma-xu/pointMLP-pytorch#55]
Can I known how do you draw the Figure 5 in your paper?

**Comment by ma-xu** [comment]
Sure.

See here: https://drive.google.com/file/d/1uHba4V3LawtWzTYuZ8FplpfosIWOZ3VP/view?usp=sharing

It is not cleaned, but it works. Feel free to modify it according to your codebase.

**Comment by 1234923iuuu** [comment]
Thanks you very much!

**Comment by RunpeiDong** [comment]
Dear authors,
Thanks for your wonderful work! May I further ask how you plot the visualization of the **plane** in **Figure 2**?
I would appreciate it if you could kindly answer my question.

**Comment by ma-xu** [comment]
@RunpeiDong  mitsuba render.

Details can be found here: https://github.com/ma-xu/pointMLP-pytorch/issues/7#issue-1154069470

**Comment by RunpeiDong** [comment]
Thanks very much for the quick response! It is a great help to me.
