### ISSUE TITLE
Source Code Repository for Part Segmentation

### ISSUE THREAD

**Issue by ShenZheng2000** [ma-xu/pointMLP-pytorch#56]
Hello, authors! I find that Line 426-445 in your [pointMLP.py](https://github.com/ma-xu/pointMLP-pytorch/blob/main/part_segmentation/model/pointMLP.py) has a significantly different format with [Pointnet2_PyTorch](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/models/pointnet2_msg_sem.py). Are you referring to another PointNet++ code repository for writing the segmentation head? Same question for your [main.py](https://github.com/ma-xu/pointMLP-pytorch/blob/main/part_segmentation/main.py) for part segmentation. 
I hope you can clarify it.
Thanks!

**Comment by ma-xu** [comment]
@ShenZheng2000 Hi, we re-organized the decoder in PointNet++, making the codes more readable and configurable.
