### ISSUE TITLE
Overall Classification Accuracy not 94.1%

### ISSUE THREAD

**Issue by merazlab** [ma-xu/pointMLP-pytorch#57]
Thanks for your contribution in Point Cloud domain,

I run your ModelNet-40 image classification model, without any changes 2 times but accuracy is not which you cited in a paper.  Our results 93.45(First experiment) and 93.6(second experiment) without voting. 

`python main.py --model pointMLP`

**Comment by ma-xu** [comment]
@merazlab Thanks for your interest.

As we clearly claimed in the ReadME file and [issue 1](https://github.com/ma-xu/pointMLP-pytorch/issues/1#issuecomment-1032642340), the performance of ModelNet40 is unstable for almost all method. We report the best performance of several runs as previous works.

**Comment by merazlab** [comment]
Hi @ma-xu,

According to your observation, what is the repeatability of OA-94.1(ModelNet-40)?

**Comment by ma-xu** [comment]
@merazlab We got the results by 6 runs. See here: https://github.com/ma-xu/pointMLP-pytorch/issues/1#issuecomment-1075338330

It would not be difficult to achieve the result. In both two versions ([submission version](https://github.com/ma-xu/pointMLP-pytorch/tree/d2b8dbaa06eb6176b222dcf2ad248f8438582026) and the current bug-fixed version), we both get the results.

**Comment by ma-xu** [comment]
@merazlab I will close this issue since no further discussions. Feel free to reopen it if necessary.
