### ISSUE TITLE
Error occurs while installing pointnet2_ops_lib

### ISSUE THREAD

**Issue by Carbord** [ma-xu/pointMLP-pytorch#58]
Hello. I followed the installation steps in readme.md., but the error occurs when installing pointnet2_ops_lib. The detailed information is shown as follows:

![)4HC44D5MQ4BQD4V97VWKZ2](https://user-images.githubusercontent.com/33995512/191404821-7125af8f-5b3b-48f5-a04e-67b354433a62.png)
![8`2~ILNAY8OGRSU6E5 %)@0](https://user-images.githubusercontent.com/33995512/191404832-db71f2d0-e0bd-4695-bbe8-b2cd98ab6614.png)

Looking forward to your help, thanks!

**Comment by ma-xu** [comment]
Hi @Carbord 
The error is: "The detected CUDA version (9.1) mismatches the version that was used to complie Pytorch (10.2). Please make sure to use the same CUDA versions".

So, what you need is to re-install Pytorch based on CUDA 9.1.  (I would suggest you can upgrade your cuda version, which is old).
To re-install right cuda-version pytorch, refer here: https://pytorch.org/get-started/previous-versions/
