### ISSUE TITLE
Local Grouper some problem

### ISSUE THREAD

**Issue by root116688** [ma-xu/pointMLP-pytorch#59]
Hi, very thank you to proivde the code, and I have few question want to know below.
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L172
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L174

1.What is different center and anchor?

------------
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L179

2.What alpha and beta learnable parameters exacalty do ?

------------
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L181

3.I don't really understand why need concat new_points?

------------
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L181

4. Why return new_xyz, but in Model forward never used?
------------
![image](https://user-images.githubusercontent.com/114909304/193532734-91edb29c-d001-4771-8b3a-6dada5bba02e.png)
5.How [512,128] convert to [256,24,128]
6.Please tell me how does it work the one stage to next stage?
7.And why repeat four times?

Thank you very much!

**Comment by ma-xu** [comment]
@root116688 Thanksfor your interest and detailed questions. Here are the responses.

1. `center` means  the mean value of the local points and `anchor` means the the selected center point. 
    We always use anchor in our implementation.
2. Alpha and beta can be considered as a common practice in normalization technologies, scaling and shifting the values. 
    Refer BN.GN,LN, etc.
3.  We notice that  this strategy would achieve better performance.
4.  it is used in https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L338
5. Using the local grouper. How  [512,128] convert to [256,24,128]? We selelct 256 points from 512 points, and consider the 24 nearest points for each selected one. The resulted tensor would be [256,24,128]
6.  Same as Q5.
7.  What do you mean by "repeat four times"? If you mean four stages, that is a common practice in network design. Other designs would be okay, but the perfomermance may vary.

Let me know if you have any further questions.

**Comment by root116688** [comment]
@ma-xu 
**1. Is "anchor" provide higher accuracy?
2. How ones and zeros to do normalization?**

3. Thanks i got it!
4. My mistake, I forget it is in for loop.
5. &6. Thanks I finally understand.
7. Thanks you again~

**Comment by root116688** [comment]
Thank you for reply many times.
            
Sorry, ones and zeros i mean self.affine_alpha and self.affine_beta , I don't understand how is this value do normalization.
Is it Layer Normalization?

this line
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ModelNet40/models/pointmlp.py#L179

**Comment by ma-xu** [comment]
They are learnable.

**Comment by root116688** [comment]
Thank you again~
