### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by OuyangJunyuan** [ma-xu/pointMLP-pytorch#6]
in LocalGrouper.forward
```python
std = torch.std((grouped_points-mean).reshape(B,-1),dim=-1,keepdim=True).unsqueeze(dim=-1).unsqueeze(dim=-1)
```
It would seem not consistent with standard deviation of local k neighborhood points in the paper?

**Comment by ma-xu** [comment]
@OuyangJunyuan  Previously, there is a bug for calculating the std. Please refer the updated arXiv version (https://arxiv.org/abs/2202.07123).

**Comment by OuyangJunyuan** [comment]
@ma-xu  and i also find some file lacked in part_segmentation.main.py `from util.data_util import PartNormalDataset`

**Comment by ma-xu** [comment]
@OuyangJunyuan Thanks for your kind remind. I will doubel check this part after Mar/10.

**Comment by ma-xu** [comment]
@OuyangJunyuan 
Thanks for your interest. I just double-checked: mistakenly uploaded the wrong folder in experiments.
Our development codes are based on PAConv, GDANet(yes), and Curevenet. We tried several implementations; as a result, we uploaded the wrong folder. You can see it in my pointsmlp repo, which is our development repo.
It is fixed now. Please have a try and let me know if there are still any issues.

**Comment by OuyangJunyuan** [comment]
> @OuyangJunyuan Thanks for your interest. I just double-checked: mistakenly uploaded the wrong folder in experiments. Our development codes are based on PAConv, GDANet(yes), and Curevenet. We tried several implementations; as a result, we uploaded the wrong folder. You can see it in my pointsmlp repo, which is our development repo. It is fixed now. Please have a try and let me know if there are still any issues.

many thanks!
