### ISSUE TITLE
About CUDA kernel error and some questions.

### ISSUE THREAD

**Issue by popopochan** [ma-xu/pointMLP-pytorch#60]
Hello, thank you for providing the code.
I just started learning about pointcloud and there are a few things I don't understand.

(1). What is the role of embedding layer in PointMLP?
(2). Which part is the Geometric Affine Module in code? Also, in Figure 6 of the paper, how many times the Geometric Affine Module appeared?
(3). Do you learn all features in one process with the entire point cloud as input, or n selected point features?

That's all I ask. Thank you very much.

**Comment by ma-xu** [comment]
Hi  @popopochan 
Thanks for your interests, here are the responses.

1. just mapping 3-d xyz to high dimensional features. 
2. See the LocalGrouper module in our codes. 4 times, each stage has one.
3. Sry that I didn't get it. We feed all the **1024** points into the network for feature extraction (classification task).

Feel free to let mw know if you have any further questions.

**Comment by popopochan** [comment]
Hi, @ma-xu 
Thank you for your timely reply.
I still have some questions.

1. I understand that this module mapping in a low dimension to high dimension, but what is the reason (purpose) for embedding?
2.I understand.  Is this the affine module before the preblock at every stage?
3. It's a neighborhood-by-neighbour process, but at the end it’s extracting all the features collectively?

Thank you.

**Comment by ma-xu** [comment]
1. Directly operating on 3-dimensional features may not achieve good performance.
2. Yes.
3. If I correctly understand your question (operating locally in each stage), the answer is yes.

**Comment by popopochan** [comment]
OK, thank you.
