### ISSUE TITLE
Why PointMLP not considered as GCN?

### ISSUE THREAD

**Issue by fmocking** [ma-xu/pointMLP-pytorch#61]
Hello, thank you for your detailed and inspiring work. After understanding the paper and reviewing the code I'm still not clear why PointMLP is classified as MLP. To the best of my understanding, it can be defined with the message-passing paradigm. Referring to the definition provided by the [Pytorch Geometric ](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.MessagePassing) can define A and Φpre in Eq. (4). Then there are Φpos operations. Again, my understanding is there is graph convolution (or message-passing) with a k-nearest neighbors graph. So, the complexity scales with N*K (N: number of points, K: kNN size), which is very similar to GNN - GCNs.  

Similarly, PointNet is defined as MLP in the paper. However, the points above are similar here. Here is the [PyG implementation of PointNet convolution](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.PointNetConv). Which is composed of local and global level neural networks. 

Based on the DGCNN definition as GCN, it is classified as GCN because it does edge-level operations rather than node level?

Again, thank you so much for your contribution.

Best,

**Comment by ma-xu** [comment]
Thanks for your insightful thoughts, i'm not an expert on GNNs. According to my **limited** understanding on GNNs, if we generalize all paradigms to a high-level concepts, they are almost the same, including gnn, attention, etc. Please correct me if i'm wrong.

**Comment by ma-xu** [comment]
Thanks for  pointing out this. 
Precisely, it should be DGCNN and cannot be simply classified as GCN. We will update it. 
Thanks for your comments.

**Comment by ma-xu** [comment]
Closed. Feel free to reopen it if you have any further questions or concerns.
