### ISSUE TITLE
About Geometric Affine Module.

### ISSUE THREAD

**Issue by popopochan** [ma-xu/pointMLP-pytorch#62]
Hi, @ma-xu
I am aware that the Geometric Affine Module overcomes the drawback of having the input point cloud transformed affine using Shared MLP.
Would this Module be effective when the input is a neighborhood patch rather than the entire point cloud?
Also, you mention that α and β are learnable parameters.
Thank you.

**Comment by ma-xu** [comment]
Probobly not. When applying to  a neighborhood path, there would be only k*d values  (k is the number of neighbors, and d is the feature dimension),  which may not be enough to get reasonable statistifcal information.

But I didn't try it. Any results are welcome.

**Comment by ma-xu** [comment]
@popopochan 
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ScanObjectNN/models/pointmlp.py#L151

**Comment by popopochan** [comment]
Thank you.
In Figure 6 of the paper, we can see that [1024, 64] ⇨ [512, 24, 64] depending on the Local Grouper. 
However, when we actually check the code, we see that the input of the Local Grouper is [1024, 64] and the output is [512, 24, 128].
Is this processed differently from the paper? (the number of channels is changing)

**Comment by ma-xu** [comment]
Same as the paper. 
What I said k*d  is in a local neighborhood path. For example, for the [512, 24, 128], 512 is number of groups, 24 is number of k-neighbors in local knn, 128 is the dimension. So, in a local neighborhood path, it would be k*d or 24*128. Hope the explanation can make it clear.  Let me know if you have any further questions.

**Comment by popopochan** [comment]
I still don't understand.
<img width="436" alt="スクリーンショット 2022-10-18 1 57 34" src="https://user-images.githubusercontent.com/80617299/196238169-0529b17a-38fe-4736-9b97-905bec37c250.png">
Affine Module is recognized as being between embedding and pre resmlp.
At this time, the embedding layer embeds the input [1024,3] into [1024,64] in multiple dimensions.
The embedded features should be used to perform an Affine transform and be used as input for pre resmlp.
However, since [512,24,64] is written under the pre resmlp, we can expect the output of the Affine module to be [512,24,64]. However, [512, 24, 128] is actually output, which I felt was processed differently from this network diagram (stage1).
I am a beginner, so sorry if my understanding is wrong.
Thanks.
