### ISSUE TITLE
Difference between new_points and grouped_points

### ISSUE THREAD

**Issue by popopochan** [ma-xu/pointMLP-pytorch#64]
@ma-xu 
I'm sorry to keep coming back to you.

Local_grouper calculates and concats new_xyz and new_points, and grouped_xyz and grouped_points, but I would like to know the difference between these two.
Also, what is the difference between fps_idx and idx?
Thank you.

**Comment by cccchensir** [comment]
fps_idx denotes the idx of sampling center points, idx denote  the idx of neighbors of center points

**Comment by ma-xu** [comment]
@cccchensir Thanks for your explanation.

@popopochan please see ccchensir's explanation. That's right.

**Comment by popopochan** [comment]
Dear @cccchensir @ma-xu 
Thank you for responses.

I have one more question.
In the geometric affine module, α and β are learnable parameters, and in the first step, α is all 1 and β is all 0, but I would appreciate it if you could tell me the process, reason, and advantage of changing it at each step.
Also, as a result, is the output point cloud affine transformed from the input point cloud?
I am a beginner. Please.
Thank you.

**Comment by ma-xu** [comment]
they are leanrable parameters implemented by nn.Parameter, will be automatically optimized and updated like parameters in learnable layers.

**Comment by ma-xu** [comment]
Closed. Feel free to reopen it if you have any further questions or concerns.
