### ISSUE TITLE
some problems about global context and cls_token

### ISSUE THREAD

**Issue by mmiku1** [ma-xu/pointMLP-pytorch#66]
Hi @ma-xu 
[gmp_list.append(F.adaptive_max_pool1d(self.gmp_map_list[i](x_list[i]), 1))](https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/part_segmentation/model/pointMLP.py#L437)

https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/part_segmentation/model/pointMLP.py#L441

The features of each layer of the encoder are concat. After max pooling,the feature is concat with the last layer of the decoder.
Why not concat with each layer of the decoder?

Thanks.

**Comment by ma-xu** [comment]
@mmiku1 It could be, but unnecessary.  Empirically, this setting can achieve promising performance.

**Comment by mmiku1** [comment]
Thank you for your answer. Wish you a happy life！
