### ISSUE TITLE
About the problem of random seed affecting the recurrence of results

### ISSUE THREAD

**Issue by fanglaosi** [ma-xu/pointMLP-pytorch#67]
hi, @ma-xu！
I really appreciate your contribution to this work.
I want to ask about the random seed. When I ran the pointMLP code myself, the results of each run were different at the situation that I fixed the random seed. What is the reason for this?
I'd appreciate it if you returned.

**Comment by ma-xu** [comment]
Closed since no further discussions. Feel free to reopen it if necessary.
