### ISSUE TITLE
about visualization

### ISSUE THREAD

**Issue by Bingo-1996** [ma-xu/pointMLP-pytorch#7]
Hi~ Can you provide the point cloud visualization code in Figure 2? Or tell me what tool was used to visualize? Thanks very much!!!

![Screenshot from 2022-02-28 21-04-07](https://user-images.githubusercontent.com/69563953/155988326-8f2491ea-b8c0-4997-9b5a-b83f20b7284f.png)

**Comment by ma-xu** [comment]
@Bingo-1996 You can use the mitsuba render.
Here is an example: https://github.com/tolgabirdal/Mitsuba2PointCloudRenderer
I guess that's what you want.

**Comment by Bingo-1996** [comment]
Got it! Thanks
