### ISSUE TITLE
About geometric affine module

### ISSUE THREAD

**Issue by LAB123-tech** [ma-xu/pointMLP-pytorch#70]
Thank you for sharing the code.

There is a question about geometric affine module. 

The funtion of this module stated in paper is that we can transform the local points to a normal distribution while maintaining
original geometric properties.

But can it really do that??????

The module consists of two main steps:

First, we need to substrct the mean value, which means substract the local center point. 

Second, we need to divide the point value by the variance.

Maybe it is a process of normalization. The mean of this point data is indeed 0 and the variance is indeed 1. 

But it cannot prove that the local points obey the trend of normal distribution.

非常感谢作者开源代码。

关于几何仿射模块有一个问题。

论文中说，局部点云数据经过该模块处理以后，那么该部分的点云数据服从正太分布。

但是真的可以做到吗？

该模块主要包含两个步骤。

第一，用局部点云的数据减去均值，其实也就是局部点云的中心点。

第二，除以方差。

这应该是一个典型的标准化的过程，此时点云数据的均值确实为0，方差确实为1。

但是此时的点云数据，应该还不是服从正太分布的吧。

**Comment by LAB123-tech** [comment]
According to the code realeased by author, I write a small example as below.

`import matplotlib.pyplot as plt
import numpy as np


def rand_data():
    return np.random.uniform(low=0., high=3., size=(200,))

data = []
x1, y1 = [rand_data() for i in range(2)]
data.append(x1.reshape(-1, 1))
data.append(y1.reshape(-1, 1))
data = np.concatenate(data, axis=1)
plt.plot(data[:, 0], data[:, 1], 'o', color='b')
plt.show()

# ----------------------------------------------------------------------------------------------------------------------

mean = np.mean(data, axis=0)
std = np.std((data-mean).reshape(1, -1), keepdims=True)
data = ((data-mean).reshape(-1, 2))/(std + 1e-5)
plt.plot(data[:, 0], data[:, 1], 'o', color='r')
plt.show()`

The final result does not show that the data follows the normal distribution.

Looking forward to your reply.

**Comment by ma-xu** [comment]
Hi @LAB123-tech

 thanks for pointing out this. Yes, this is definitely not a normal distribution, it is like a normalization. We will update our arrival paper in case of any misleading. Thanks for your kind reminder.

Best,
Xu

**Comment by LAB123-tech** [comment]
邮件已经收到，我是李阿标。

**Comment by ma-xu** [comment]
@LAB123-tech We have just updated this in arXiv, as well as some other small errors (e.g., DGCNN in Table 1, references, etc.). Thanks again for your kind reminder.

**Comment by LAB123-tech** [comment]
邮件已经收到，我是李阿标。
