### ISSUE TITLE
Farthest point sampling torch implementation

### ISSUE THREAD

**Issue by plpplp** [ma-xu/pointMLP-pytorch#73]
### Farthest point sampling torch implementation

``        @mahaotian-io Hi, they are the same, but the self-defined function defined farthest_point_sample is in python and .furthest_point_sample is in cuda. We use the cuda version for fast training and inference.

_Originally posted by @ma-xu in https://github.com/ma-xu/pointMLP-pytorch/issues/47#issuecomment-1186800256_
      
Hi, I just checked the function `farthest_point_sample` and I think it works a little bit different than one might expect. I wonder if `farthest_point_sample` works as intended. The difference in my quick numpy implementation of fps (`furthest_point_sampling`) is that I keep track of which points have already been sampled when calculating distances. 

I just tested the code of this repo with the below lines and the sampled points of this repo seem to cover the point set not _that_ good. 

```
import torch
xyz = torch.randint(0, 30000, (10, 1000, 3)).contiguous()

num_samples = 50

fps = farthest_point_sample(xyz, num_samples)
fps = index_points(xyz, fps).numpy()

red, green, blue = [1., 0., 0.], [0., 1., 0.], [0., 0., 1.]

# only plot first sample of batch
plt.scatter(xyz[0, :, 0], xyz[0, :, 1], c=blue)
plt.scatter(fps[0, :, 0], fps[0, :, 1], c=red, label='fps, pointMLP')

nfps = furthest_point_sampling(xyz[0, :, :2].numpy(), num_samples)
plt.scatter(nfps[:, 0], nfps[:, 1], c=green, label='fps')
plt.legend()
```
I will add a plot later, github seems to have trouble accepting my file upload currently.

**Comment by ma-xu** [comment]
@plpplp Hi, thanks for the detailed  information. 

The python function `farthest_point_sample` is from https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/eb64fe0b4c24055559cea26299cb485dcb43d8dd/models/pointnet2_utils.py#L63

The cuda function `furthest_point_sample` is from https://github.com/erikwijmans/Pointnet2_PyTorch

We use the cuda function `furthest_point_sample ` for our implementation (the python function `farthest_point_sample` is used for debug and development in local Mac). 

Feel free to add a plot later (you can copy a link to the figure and codes) and that would be much helpful to check if any issues.

**Comment by plpplp** [comment]
Hey, thankts for the quick response. Here is the code for my version of fps:
<script src="https://gist.github.com/plpplp/f382c85fd217b40d9964a2dfed45f831.js"></script>
and this is the figure.
![fps](https://user-images.githubusercontent.com/35866884/209798250-50f9881b-5df3-4913-94e5-7b5741bab68a.jpg)
In red below are the sampled points using the implementation of this repository. In green the quick implementation from above of fps that covers the randomly generated point set somewhat better. It probably is fine though if the function is meant for debugging purposes only. I thought I could use it for a rather small dataset so that I do not have to compile those kernels for my initial tests.

**Comment by plpplp** [comment]
Algo seems to work fine, my bad, I made the mistake to calculate the 3d distance of the points and projected them onto the 2d plane in my plot to compare the two implementations. Thanks :).

**Comment by ma-xu** [comment]
Thanks, very interesting and also very helpful to see the selected points.
