### ISSUE TITLE
Fail to install "pointnet2_ops_lib/."

### ISSUE THREAD

**Issue by zhangHH1998** [ma-xu/pointMLP-pytorch#74]
I also have the same question, and when I try to solve it on the net, it asks me to install Visual Studio tools, but it's useless. The detail as follow:
![image](https://user-images.githubusercontent.com/103565024/210740481-978fe651-da93-405f-831e-6341ddca0873.png)
![image](https://user-images.githubusercontent.com/103565024/210740595-8e2b6814-6d50-461c-b424-10d05f442097.png)
![image](https://user-images.githubusercontent.com/103565024/210740777-5735ecfe-a447-4b2c-802d-384d825bc308.png)

**Comment by ma-xu** [comment]
Thanks for your interest. We didn't test Windows.
