### ISSUE TITLE
Cite your work

### ISSUE THREAD

**Issue by xiaobaitu123344** [ma-xu/pointMLP-pytorch#79]
Thank you very much for your creative work, I would like to cite your paper, but have encountered a small problem about how to use from torchstat import stat to calculate FLOPs.

**Comment by ma-xu** [comment]
We didn't report the flops because some operations are implemented by cuda. You can try https://github.com/facebookresearch/fvcore

**Comment by xiaobaitu123344** [comment]
Thank you very much for your answer
