### ISSUE TITLE
ScanObjectNN evaluation

### ISSUE THREAD

**Issue by EternityDS** [ma-xu/pointMLP-pytorch#8]
Hi,

Thanks for your great work! I really like this idea and your brilliant paper-writing! I have a quick question about ScanObjectNN evaluation.

I notice this dataset has many variants shown in their paper, such as *objectdataset.h5, *objectdataset_augmentedrot_scale75.h5. And I think the result in PointMLP is based on *objectdataset_augmentedrot_scale75.h5.

May I ask is this the default setting to use this variant for ScanObjectNN classification task? And do you think all the results [here](https://paperswithcode.com/sota/3d-point-cloud-classification-on-scanobjectnn) use the same variant?

Thank you!

**Comment by ma-xu** [comment]
@EternityDS  Thanks for your interest!
I would same it may not be the default setting, but most people are using this one (because of the difficulty).
They are using the same variant. I double-checked the papers and codes. 

Also, you can present the results of all the variants as in some papers.

**Comment by EternityDS** [comment]
Thanks for your reply!
