### ISSUE TITLE
How to create the virtual environment?

### ISSUE THREAD

**Issue by Waseda-Niuniu** [ma-xu/pointMLP-pytorch#86]
Thank you for your exciting work !!!
I found conflicts when I  `conda env create`
Could you update the environment.yml？

**Comment by Waseda-Niuniu** [comment]
I solved the problem of environment configuration by installing docker! 
Thank you for your code, I will study it.

**Comment by suhansu** [comment]
> for

Hi~,bro can i see you dockerfile?
