### ISSUE TITLE
Hyperparamater about experiment on ScanObjectNN

### ISSUE THREAD

**Issue by liller** [ma-xu/pointMLP-pytorch#87]
Thanks so much for your work! @ma-xu 

I also try to train the model on ScanobjectNN ds with the hyperparameter for 200 epochs. But there is a degree of over-fitting. Are there any methods to alleviate this problem and could you analyse why the over-fitting is more significant on this dataset? Because ScanObjectNN is actually more complex and challenging than ModelNet40.

Many thanks in advance.

**Comment by ma-xu** [comment]
Hi, thanks for the issue. Currently no specific idea on this. However, both ModelNet40 and ScanObjectNN are small datasets, probably we need a significantly larger dataset.
