### ISSUE TITLE
About ShapeNet Part evalaution

### ISSUE THREAD

**Issue by de-gozaru** [ma-xu/pointMLP-pytorch#9]
Hi,

Thank you for sharing the code.

I'm intersted in the segmentation experiment.

In fact, in the `part_segmentation/main.py` file, in line 13, you import this:
```
from util.util import to_categorical, compute_overall_iou, IOStream
```
But I could not find it in the repository, where can I get these functions?

Thank you in advance.

**Comment by ma-xu** [comment]
@de-gozaru  See here: https://github.com/ma-xu/pointMLP-pytorch/issues/6#issuecomment-1053660028
 We will doubel check this part after Mar/10.

BTW, our part segmentation codes are taken from https://github.com/mutianxu/GDANet and https://github.com/CVMI-Lab/PAConv/

**Comment by Chen-yuiyui** [comment]
Hoping for the full code of part segmentation,thank you .

**Comment by ma-xu** [comment]
@Chen-yuiyui @de-gozaru 
Thanks for your interest. I just double-checked: mistakenly uploaded the wrong folder in experiments. 
Our development codes are based on PAConv, GDANet(yes), and Curevenet. We tried several implementations; as a result, we uploaded the wrong folder. You can see it in my pointsmlp repo, which is our development repo.
It is fixed now. Please have a try and let me know if there are still any issues.

**Comment by ma-xu** [comment]
@Chen-yuiyui @de-gozaru I will close this issue since there is no further discussion. Feel free to reopen it if necessary.
