### ISSUE TITLE
Download Link of ModelNet40 Not Working

### ISSUE THREAD

**Issue by ziqipang** [ma-xu/pointMLP-pytorch#90]
Dear authors,

Thank you for the great work of PointMLP and for generously sharing the code! Recently, I tried to run your code but found the link to download ModelNet40 not working. If it is possible, could you please share a link to your file or send it to me via email (ziqip2@illinois.edu)? Greatly appreciate it!

Best,

Ziqi

**Comment by ma-xu** [comment]
Sure, you mean the modelNet40 checkpoint or original dataset?

**Comment by ziqipang** [comment]
Thanks for the prompt rely! The file of line (https://github.com/ma-xu/pointMLP-pytorch/blob/3e3d80cff5c23a631fe5ba4ca97db3f452893ed2/classification_ModelNet40/data.py#L14) would be enough.
