### ISSUE TITLE
Method about rending point cloud

### ISSUE THREAD

**Issue by LAB123-tech** [ma-xu/pointMLP-pytorch#91]
Hi, It's a nice job. Could you please tell how do you rendering point cloud in the paper like figure 2, as shown in the below.
![image](https://github.com/ma-xu/pointMLP-pytorch/assets/84617754/468d2fcc-50fb-4b3c-928c-45a4d27c061f)

**Comment by DeVriesMatt** [comment]
@LAB123-tech check out this [repo](https://github.com/tolgabirdal/Mitsuba2PointCloudRenderer)

**Comment by LAB123-tech** [comment]
Thanks very much.
