### ISSUE TITLE
CPU not supported

### ISSUE THREAD

**Issue by xje123456** [ma-xu/pointMLP-pytorch#92]
RuntimeError: false INTERNAL ASSERT FAILED at "pointnet2_ops\\_ext-src\\src\\sampling.cpp":83, please report a bug to PyTorch. CPU not supported

**Comment by lysukhin** [comment]
I belive you tried to run something like `python pointmlp.py` in order to test the model.
I met the same error, and actually if you move both of `data` and `model` to GPU (adding `.cuda()`), everything would work fine.

**Comment by ma-xu** [comment]
Thanks for sharing. Since no more discussions, let me close this issue.

**Comment by JiangWeiHn** [comment]
I want run it on CPU!!!  What can  i do ??

**Comment by ma-xu** [comment]
@JiangWeiHn This might be what you want.
https://github.com/ma-xu/pointMLP-pytorch/issues/63#issuecomment-1281071653
