### ISSUE TITLE
Equivariance in PointMLP

### ISSUE THREAD

**Issue by smiles724** [ma-xu/pointMLP-pytorch#93]
Hi thanks for your sharing. 
However, I am curious about your initialization of point embeddings. You used a Conv1D to initialize the point feature, where the input channel is 3, the coordinates of each point. 

I wonder whether this kind of initialization can lead to different results when the coordinate system changes. In other words, how do you ganrantee the equivariance of your network? 

![image](https://github.com/ma-xu/pointMLP-pytorch/assets/39299863/f665e9d5-5879-476b-a1f8-95fc8da75077)

**Comment by smiles724** [comment]
Please see more direct figure in your paper. You directly change (1024, 3) to (1024, 64). 
![image](https://github.com/ma-xu/pointMLP-pytorch/assets/39299863/8f2c8772-3ba8-48f1-96d9-9f9661f13f22)

**Comment by ma-xu** [comment]
Since no more discussions, let me close this issue.
